spring:
  application:
    name: demoservice
server:
  port: 8080

---
spring:
  profiles: dev
  application:
    name: demoservice
server:
  port: 9090

#logging
debug: false
logging:
  path: D:\working\projects\demo\logs
  level:
    root: info
---
spring:
  profiles: prod
  application:
    name: demoservice
server:
  port: 4431
